### ISSUE TITLE
Typo in package.swift

### ISSUE THREAD

**Issue by tklightningfast** [kinkofer/PokemonAPI#12]
Hello! I think you have a typo in Package.swift (called it "PokemomAPI"). I think you should also update the README to reflect that this repo is compatible with Swift Package Manager (as far as I know, I don't see any problems using it). I would perform these changes myself, but I'm not really sure how contribution works on github.

**Comment by kinkofer** [comment]
Thanks for pointing this out. I've made the fix and updated the README.
