### ISSUE TITLE
resourceService doesn't work

### ISSUE THREAD

**Issue by tklightningfast** [kinkofer/PokemonAPI#15]
As of the moment, the pokemonAPI resource service does not work; it only returns error code 404 from the server.
The bug seems to be occurring in the declaration here:
```swift
public struct ResourceService: PKMResourceService {
    public enum API<T>: APICall {
        case fetchResource(PKMAPIResource<T>)
        
        var path: String {
            switch self {
            case .fetchResource(let resource):
                return resource.url ?? ""
            }
        }
    }
    ...
}
```
```PKMAPIResource``` by default comes with the baseURL attached, so the declaration of `path` as just the url without removing the baseURL results in a problem down the propagation, where the baseURL is appended again, resulting in garbage urls like `https://pokeapi.co/api/v2https://pokeapi.co/api/v2/pokemon-species/1/`. 

I'm currently working on a pull req to fix this, as well as add a test.

**Comment by kinkofer** [comment]
Thanks for finding. I really need to get the whole API fully tested soon.
I think a sufficient fix is just removing the baseURL for the ResourceService. I've done this in #17.
