### ISSUE TITLE
PKMAPIResource instead of Named

### ISSUE THREAD

**Issue by AHoxha19** [kinkofer/PokemonAPI#22]
When using the fetchPokemonList method, i thought that the list should return the name of the pokemon instead of the URL only. If we look at the `PKMPagedObject` class we see this private attribute :

```
  /// List of named API resources
    public private(set) var results: [PKMAPIResource<T>]? 
```

The result and the comment are misleading because we expect to receive something like: `{name: "bulbasaur", url: "url"}` instead of: `{url: "url"}`.

The PokeApi returns a named resource when we call the '/pokemon' endpoint. Can we change the object returned to: **PKMNamedAPIResource** ?

**Comment by kinkofer** [comment]
Not every service returns a "named" resource, so changing the type would cause it to fail in those cases. I can update the comment though: 
`/// List of API resources (some services return named resources and can be cast as [PKMNamedAPIResource])`

And I provide an example of this in PaginatedResultsView:
`let pokemonResults = pagedObject.results as? [PKMNamedAPIResource]`

**Comment by AHoxha19** [comment]
Thanks, i did not see that we needed to cast !
